name: toomanynames
markdown: redcarpet
highlighter: pygments
poet_url: /poet
excerpt_separator: <!--more-->
programmer_url: /programmer
url: /
featured: ['all', 'poet', 'programmer', 'about']
suggested_tweet:
    url:                  'http://toomanynames.com'
    text:                 'This was cool!'
    hashtags:             ['PoetProgrammer']
    related: 			  'anirudh_eka'