name: toomanynames
summary: The writings of <a href="https://twitter.com/anirudh_eka" target="_blank">Anirudh "Eka"</a>, a poet and software developer passionate about alternative education, creativity, and finding peace in here and out there.
markdown: redcarpet
highlighter: pygments
poet_url: /poet
excerpt_separator: <!--more-->
programmer_url: /programmer
url: /
featured: ['all', 'poet', 'programmer', 'about']
suggested_tweet:
    url:                  'http://toomanynames.com'
    text:                 'This was cool!'
    hashtags:             ['PoetProgrammer']
    related: 			  'anirudh_eka'