name: toomanynames
summary: The writings of <a href="https://twitter.com/anirudh_eka" target="_blank">Anirudh "Eka"</a>, a poet and software developer passionate about alternative education, creativity, and finding peace in here and out there.
summary_as_plain_text: The writings of Anirudh 'Eka', a poet and software developer passionate about alternative education, creativity, and finding peace in here and out there.
markdown: redcarpet
highlighter: pygments
poet_url: /poet
excerpt_separator: <!--more-->
programmer_url: /programmer
url: /
featured_categories: ["code", "poetry & essays", "projects"]
future: true
suggested_tweet:
    url:                  'http://toomanynames.com'
    text:                 'This was cool!'
    hashtags:             ['PoetProgrammer']
    related: 			  'anirudh_eka'
defaults:
    image_file: sipping_tea.jpg
