name: toomanynames
markdown: redcarpet
pygments: true
poet_url: /poet
programmer_url: /programmer
url: /
suggested_tweet:
    url:                  'http://toomanynames.com'
    via:                  'anirudh-eka'
    text:                 'This was cool!'
    hashtags:             ['PoetProgrammer']
    related:              ['anirudh_eka']